version: '3.8'

services:
  app:
    build:
      context: ./panto-health
      dockerfile: Dockerfile
    container_name: panto-health-app
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - mongo

  producer:
    build:
      context: ./panto-health-producer
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: panto-health-rabbitmq
    ports:
      - '5672:5672' # AMQP protocol port
      - '15672:15672' # Management UI port
    env_file:
      - .env
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  mongo:
    image: mongo:latest
    container_name: panto-health-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env

volumes:
  mongo-data:
  rabbitmq-data: