version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: panto-health-app
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: panto-health-rabbitmq
    ports:
      - '5672:5672' # AMQP protocol port
      - '15672:15672' # Management UI port
    env_file:
      - .env